version: '3.4'

services:
  web:
    build:
      context: .
      args:
        # bump this to force new data
        - "CACHE_VERSION=${CACHE_VERSION:-0}"
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - '8070:80'
