#!/bin/bash
# Use in dev to rebuild the assets for the server running from 'docker-compose up'.

set -e

docker-compose -f docker-compose.scripts.yml build --force-rm build-assets

docker-compose -f docker-compose.scripts.yml \
  run -T --rm build-assets \
  | tar xv -C public

sed -i -e "s@app-.*.js@app.js@" public/index.html
bash script/bust-js-cache public/index.html app.js
