#!/bin/bash

datadir="$(dirname "$0")/../data"
mkdir -p $datadir
cd $datadir

curl -LO https://github.com/nytimes/covid-19-data/raw/master/us-states.csv
curl -LO https://github.com/nytimes/covid-19-data/raw/master/us-counties.csv

curl -LO https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
